vse: &vse
  docker:
    - image: circleci/node:8.11.3
version: 2.1
jobs:
  test:
    <<: *vse
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - persist_to_workspace:
          root: .
          paths:
            - . 
            
  build:
    <<: *vse
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build

  
  deploy:
    <<: *vse
    steps:
      - attach_workspace:
          at: .
      - run:
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
workflows:
  version: 2.1
  build:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
